language: node_js
node_js:
- node
git:
  depth: false
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAI6NYC34CCPWOMVUA
  secret_access_key:
    secure: KJeYq9T8O1MsArF7CVGWi1PKPLZxojX2RPj9kuCdH1jAA7zrCd2T+gm/JM7FXIM83RHG7keReLXBIlftcwemiAcNVNLrtWSQKhI5sqCzCuLltSV+L8OKuRj6ILMYHCQtZXCfSoQ9TOWYVA07XfolCGL6cQRB/gwDENby3+9xfrgG88TQ7/zaz5TG5yu1+nBz1+3OImNsN2uU1UGNYCz+W34t3v2HxsVTk36ug3mJ1bKVKPGnTF5eAYuuxzjfKWlQOnQccX/fp+1dDfxec1Z9++AUcJ09y8s0ekQOzun17sSuV1j9dTIi5sA99tCmPKd6OcCxgSJUNL3CvMnTkKeX6PT7+zZqs+VT1u4uGnsOzyRgtNP75AydSKNy4PnIsPVXH2DCq9nEjGe4j10opspwnnW7Vj1CEhsDA/YnQhxo68ur79WQIg1efpc5kqFHNjfTnRgqaR52ut0R+E1s0iGSnli3hwzFRTAlZ1IMpGPlJ2smuhRqjdfiDWahLHrtYtPYMkYu6TBT25fJCVJVXI6cThYYlNXDz+pgLmadztLH+b9XrcHx+AlnUtnjiKzbCqnrncQ82jWyXVdnIlCc74UgLLK37cJ4ZVSJclXOi7V0Tj4wyy95o0tIfUtHtpXI0/fdlc/6SU5T+NsIWDwd5CtLNjL2eTR/n+vxoxphvt33Vvw=
  bucket: jonathanmp.me
  region: us-east-2
  local-dir: dist
  on:
    repo: jonathanp727/portfolio-react
