language: node_js
node_js:
- node
git:
  depth: false
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIB4DVUDUJQM4M3OA
  secret_access_key:
    secure: W/rtp/Uzan78ICPhd0cx7j10b8/PxR4fXTX41gfy4TYfU5YYdaAZEB0RaZTCGLBJusQ2bn67HEWjZKapQBsFClMGgIiuWIUdMaIVth46VNvWTq7EdAY6RU170BPYndresqFKIEcU8viQilIpM1VDtn9NrkFMzd2yn0wTbC/OqHbXuBK/R/43vE3ohTNkgsGyUxMO6roWtfzetdY4aFqCZp0B65U1xy0rJ/nbNtGLsh368WWYLZfcR//mDsLFMVnxpS9+Nr0BZvYVog5g7qhrzGyJ2zFQcIFLlILDp82S1Je4qZWDIu5GoPnLPw/CBmj6UT2UyYDAdYCBCmKtGxaLNPb+8XLxXWNtM24ANVI2KNsQ//zgtfO1ZbvyjLl/x0QRvxPSbQqbYmsXZ7K3406KkoFJOBlcIb81YRU4CrrUx1hsvPJh6n7FKgFN29Zt7HgklRN34JqzuPgDUatd1zEkx5vMaIHUF7L4aiZ8WPupHUqdUFMvGJ9UmiqNlxnm4CXyTaDNXPY+svzmdpj86ukvW/oSccfYA6PD3l/3SRVXqb5o67m0QsTIalpit2ENExYKEofRFexbB9p9gpQ6mul1skyWOUpUPQyGPqpjiDhXsfo5ZMCG2E37id1zY3Xr9gzz3WYQb46BKhTQJaue6goX4GLZ2SGdlqKXVItzirhQ/EA=
  bucket: jonathanmp.me
  region: us-east-2
  local-dir: dist
  on:
    repo: jonathanp727/portfolio-react
